name: CI MAIN

on: [push,workflow_dispatch]

jobs:
  call-docker:
    uses: testVinaycicd/learn-1-terraform/.github/workflows/ci-main.yml@main   # must include @ref
    with:
      tag: ${{ github.sha }}

  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          if  [ -z "${{ secrets.DEBUG_PAT }}" ]; then
            echo "ERROR: Docker secrets missing or not available in this run."
            echo "Add DOCKERHUB_USERNAME and DOCKER_TOKEN in repo Settings → Secrets → Actions."
            echo "If this is a forked PR, secrets are not exposed — run on a branch in this repo."
            exit 1
          fi
          echo "Docker secrets present (masked)."
